### ISSUE TITLE
m1 pro 找不到SQLCipher依赖

### ISSUE THREAD

**Issue by sxhxliang** [qwertyyb/Fire#101]
<img width="1512" alt="Screenshot 2023-04-18 at 15 44 03" src="https://user-images.githubusercontent.com/8338091/232707965-8a3a4f6b-4ee1-42f0-b353-f8cb3f5d50a1.png">

我更新了一下，还是找不到

```
❯ pod update
Update all pods
Updating local specs repositories
Analyzing dependencies
Downloading dependencies
Installing SQLCipher 4.5.3 (was 4.5.1)
Installing SwiftLint 0.51.0 (was 0.47.1)
Generating Pods project
Integrating client project
Pod installation complete! There are 7 dependencies from the Podfile and 7 total pods installed.

[!] The `Fire [Debug]` target overrides the `PODS_CONFIGURATION_BUILD_DIR` build setting defined in `Pods/Target Support Files/Pods-Fire/Pods-Fire.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

```

**Comment by qwertyyb** [comment]
https://stackoverflow.com/questions/69665207/library-not-found-for-lfolly 看一下这里

**Comment by sxhxliang** [comment]
> https://stackoverflow.com/questions/69665207/library-not-found-for-lfolly 看一下这里

好像不是这个问题

**Comment by qwertyyb** [comment]
你按这个上面的操作，把对应的库换成SQLCipher即可

**Comment by sxhxliang** [comment]
这个问题还是没有解决，不知哪里出现问题了

**Comment by sxhxliang** [comment]
> 你按这个上面的操作，把对应的库换成SQLCipher即可

Xcode Version 14.3 (14E222b) 编译是不是有问题

**Comment by xiaoqiao** [comment]
关注一下，这个问题解决了么？

**Comment by sxhxliang** [comment]
> 关注一下，这个问题解决了么？

你也出现这个问题么

**Comment by qwertyyb** [comment]
最近升级了装备，我这边使用M2，没有出现类似问题
而且目前我把依赖从cocoapods切到了spm, SQLCipher内置了，可以再试试看

**Comment by ShikiSuen** [comment]
@qwertyyb 借地方打听一下。
我看您的 SQLite 是自备了 Almagation 原始码、而没有直接使用 macOS 内建的 SQLite。
请问这是否是为了给资料库加密？还是有其他的考量？

（通常情况下 Swift 可以直接 import SQLite3 来使用 SQLite，除非像是 macOS 10.9 这种超老的系统版本才需要自备 Almagation。）
