### ISSUE TITLE
每次更新之后，需要重启才能使用

### ISSUE THREAD

**Issue by yingguqing** [qwertyyb/Fire#106]
![image](https://user-images.githubusercontent.com/6702678/236726973-4b2db86a-900c-415f-aa14-93dfad4525e4.png)
每次更新了输入法，一切换就弹这个提示。同意都没用，重启才可以。
系统：13.2.1 (22D68)

**Comment by ShikiSuen** [comment]
@qwertyyb 请问您这输入法涉及到 TISInputSource 安装登记的部分在哪些档案当中？

我这边把 TIS 相关的内容都用 Swift 包装了一下。
https://github.com/vChewing/vChewing-macOS/blob/08f56c1009160d18caec5cf5d4223e02c20796b2/Packages/vChewing_IMKUtils/Sources/IMKUtils/TISInputSourceExtension.swift#L28

**Comment by ShikiSuen** [comment]
没能找到 TextInputMenuAgent 的源码。难道这是 macOS 系统内建的组件？

**Comment by chengpan168** [comment]
安装的时候也遇到了， 需要重启才能生效

**Comment by qwertyyb** [comment]
> 安装的时候也遇到了， 需要重启才能生效

你这边是首次安装还是更新安装后需要重启呢？

**Comment by chengpan168** [comment]
> > 安装的时候也遇到了， 需要重启才能生效
> 
> 你这边是首次安装还是更新安装后需要重启呢？

情况是： 第一安装之后不记得有没有重启了， 后面不用百度输入法了， 把Input Methods 里的手抖全删了， 重启后再次安装Fire， 没有出现， 重启后出现了。 我这个不具有代表性算是特殊情况吧。

**Comment by qwertyyb** [comment]
按我这边的测试结论来看：
1. 首次安装应该是不用重启直接就能使用
2. 更新安装时，需要重启 或者 在系统设置->键盘->输入法->编辑，先删除再添加输入法才能在菜单栏看到图标并选中

我这边的系统是14.5

**Comment by chengpan168** [comment]
> 按我这边的测试结论来看：
> 
> 1. 首次安装应该是不用重启直接就能使用
> 2. 更新安装时，需要重启 或者 在系统设置->键盘->输入法->编辑，先删除再添加输入法才能在菜单栏看到图标并选中
> 
> 我这边的系统是14.5

好， 下次更新时试一下， 用了几天了， 很好用， 5分好评
