### ISSUE TITLE
输入没有上屏时让输入框失去焦点不会隐藏候选框

### ISSUE THREAD

**Issue by khawa-source** [qwertyyb/Fire#111]
已输入的内容没有上屏时（没有提交时）让客户端输入框失去焦点，应该要提交 _originalString 且隐藏候选框

**Comment by ShikiSuen** [comment]
请问这 _originalString 可是尚未组笔的组笔区字根？

**Comment by khawa-source** [comment]
> 请问这 _originalString 可是尚未组笔的组笔区字根？

是的 不管 _originalString 是否可以正确提交 但候选面板应该是要隐藏的

**Comment by ShikiSuen** [comment]
窃以为不应该断言「应该要提交 _originalString 且隐藏候选框」。
这个特性干脆做成可选功能比较好。有些在乎私隐的人不希望尚未完成组字的内容被递交出去。

目前有个担忧就是：一个输入法控制会话副本的 deactivateServer() 可能会晚于另一个新的当前控制会话副本的 activateServer() 执行。

**Comment by ShikiSuen** [comment]
<img width="1335" alt="image" src="https://github.com/qwertyyb/Fire/assets/3164826/2c3fd402-3fae-400f-9279-50639cc51287">

我看目前的 codebase 里面是有间接指定在 deactivateServer 的时候隐藏选字窗的。
@khawa-source 请问您是否在用最新版本的业火五笔输入法？

**Comment by qwertyyb** [comment]
> 窃以为不应该断言「应该要提交 _originalString 且隐藏候选框」。 这个特性干脆做成可选功能比较好。有些在乎私隐的人不希望尚未完成组字的内容被递交出去。
> 
> 目前有个担忧就是：一个输入法控制会话副本的 deactivateServer() 可能会晚于另一个新的当前控制会话副本的 activateServer() 执行。

对，这个问题我也发现了，我当时是在Safari浏览器的地址栏中使用出现的此问题，所以当时不得不改动了一些逻辑，把原本放在deactivateServer中的逻辑放在了activateServer中，比如图中的previousClientHandler，比如关闭候选窗

**Comment by ShikiSuen** [comment]
@qwertyyb 只是个理论上的说法哈：

老副本在 deactivateServer 的时候，检查选字窗是否有在显示。
如果有在显示的话，检查其绑定的副本是否是 deactivateServer 自身所在的副本。
如果不是的话，就不用关闭；如果是的话，关闭之。

**Comment by ShikiSuen** [comment]
我发现问题了。 ＠qwertyyb 您这边 commitComposition() 没实作。
我稍后推个 PR。

**Comment by qwertyyb** [comment]
> 我发现问题了。 ＠qwertyyb 您这边 commitComposition() 没实作。 我稍后推个 PR。

什么问题？是说没有上屏时，输入框推动焦点不会隐藏候选框的问题吗？

**Comment by ShikiSuen** [comment]
@qwertyyb 有些客体应用在输入框失去焦点的时候，不是呼叫 deactivateServer，而是呼叫 commitComposition()。

这样吧，我写出来了，您直接塞进去、再看着修改一下（因为需要牵涉到 Defaults 的新 Key）：

```swift
extension FireInputController {
    override func commitComposition(_ sender: Any!) {
      // TODO: 回头加个开关让用户决定这里的行为是下述任一：
      // 「递交目前的第一候选字」「递交原始字根」「啥也不递交」。
      insertText(_originalString) // 就是规范这句，让用户决定该递交啥内容。
      clean()
      NSLog("[FireInputController] commitComposition(): \(client()?.bundleIdentifier() ?? "no client calls commitComposition()")")
    }
}
```

**Comment by qwertyyb** [comment]
@ShikiSuen  你有使用过 commitComposition 吗？可靠性如何？我其实有些不太信任 InputMethodKit 中的一些方法，我在 override 这些方法时都比较克制，这里的改动容我后面验证一下

**Comment by ShikiSuen** [comment]
@qwertyyb 威注音没实作这个 API 的后果就是在微信当中换行时组字区没被清空，因为微信在讯息输入窗格内换行时会呼叫一次 commitComposition()。

https://developer.apple.com/documentation/objectivec/nsobject/1385539-commitcomposition

> If an input method implements this method, it is called when the client wants to end the composition session immediately. A typical response would be to call the insertText method of the client and then clean up any per-session buffers and variables. After receiving this message an input method should consider the given composition session finished.

**Comment by qwertyyb** [comment]
<img width="1201" alt="图片" src="https://github.com/qwertyyb/Fire/assets/16240729/28a2171d-7c03-415d-afe0-ed9726f7bd14">
我这里之前有一个提交特意注释了这一点，不过时间有些久，我不记得是在哪个场景有问题了。好像也是在微信吧

**Comment by ShikiSuen** [comment]
拿威注音来讲的话：

- deactivateServer() 会将当前组字区内容清空＋将输入法当前输入会话的有限态械的状态改成 .ofDeactivation。
- commitComposition() 会将当前组字区内容清空，但输入法当前输入会话的有限态械的状态也只是打回 .ofEmpty 而已。

**Comment by ShikiSuen** [comment]
一言以蔽之：commitComposition 就是打折版的 deactivateServer。就业火五笔目前的情况而言，两个都是 clean 的话也不过份、且前者先递交再 clean()。

（我修改了我前一条回覆。）

**Comment by ShikiSuen** [comment]
@qwertyyb 喔对了：

论及这些需要 override 的 API 在 IMKInputController 原始 Class 当中的行为究竟是不是「什么也没做」，您可以对 macOS 10.15 Catalina 内建的 IMK 做逆向工程（之后的 macOS 好像不能这么做了）。

这是我这边看到的 commitComposition 的内容：

<img width="1920" alt="image" src="https://github.com/qwertyyb/Fire/assets/3164826/a9fd1dbd-6ae0-475c-b615-ede9b799289d">

如果您希望保持这个函式原厂的行为不变的话，那也得是（比我上文多了一句 `super.commitComposition(sender)`）：
```swift
extension FireInputController {
    override func commitComposition(_ sender: Any!) {
        super.commitComposition(sender)
        clean()
        NSLog("[FireInputController] commitComposition(): \(client()?.bundleIdentifier() ?? "no client calls commitComposition()")")
    }
}
```

**Comment by qwertyyb** [comment]
> @qwertyyb 喔对了：
> 
> 
> 
> 论及这些需要 override 的 API 在 IMKInputController 原始 Class 当中的行为究竟是不是「什么也没做」，您可以对 macOS 10.15 Catalina 内建的 IMK 做逆向工程（之后的 macOS 好像不能这么做了）。
> 
> 
> 
> 这是我这边看到的 commitComposition 的内容：
> 
> 
> 
> <img width="1920" alt="image" src="https://github.com/qwertyyb/Fire/assets/3164826/a9fd1dbd-6ae0-475c-b615-ede9b799289d">
> 
> 
> 
> 如果您希望保持这个函式原厂的行为不变的话，那也得是（比我上文多了一句 `super.commitComposition(sender)`）：
> 
> ```swift
> 
> extension FireInputController {
> 
>     override func commitComposition(_ sender: Any!) {
> 
>         super.commitComposition(sender)
> 
>         clean()
> 
>         NSLog("[FireInputController] commitComposition(): \(client()?.bundleIdentifier() ?? "no client calls commitComposition()")")
> 
>     }
> 
> }
> 
> ```

倒不是因为override方法的默认行为，而是它的方法调用时机不太可控

**Comment by ShikiSuen** [comment]
@qwertyyb 但 commitComposition 是可控的。Google MOZC 内部开发手册里面有写：
<img width="678" alt="image" src="https://github.com/qwertyyb/Fire/assets/3164826/f8bca84d-ebd8-4bfe-bbb1-507db2cf62e9">
https://github.com/google/mozc/blob/d0f8e09cdcf9d6e23ccc83b0a118162e5a05a934/docs/design_doc/mac_internal.md?plain=1#L137C1-L140

**Comment by ShikiSuen** [comment]
这是谷歌日语输入法（MOZC）的 commitComposition 实作：
<img width="652" alt="image" src="https://github.com/qwertyyb/Fire/assets/3164826/4cff689c-f035-49c9-b011-1520f114f9f1">

**Comment by qwertyyb** [comment]
好的，我接下来会再进行验证，看是否要如此处理

**Comment by ShikiSuen** [comment]
> <img alt="图片" width="1201" src="https://user-images.githubusercontent.com/16240729/269566931-28a2171d-7c03-415d-afe0-ed9726f7bd14.png"> 我这里之前有一个提交特意注释了这一点，不过时间有些久，我不记得是在哪个场景有问题了。好像也是在微信吧

@qwertyyb  你这篇当中的关于 Xcode 搜索框那个问题呢，是 Xcode 的 Bug。我用 macOS 内建的日语输入法测试也发现了故障：用空白键叫不出选字窗、而是 Space 击键事件被直接送给客体了。

**Comment by qwertyyb** [comment]
@khawa-source 已处理支持
