### ISSUE TITLE
标点符号的问题

### ISSUE THREAD

**Issue by JonyChuh** [qwertyyb/Fire#118]
Fire是我用过的最好用的五笔输入法，非常感谢！有一个小问题，中文标点符号的双引号只能输半个，而不是成对出现，以前用过的输入法是这样设计的，按一次先上屏左半个，再按一次则上屏右半个。英文标点貌似左右半个都是一样的，可能不存在这样的问题。

**Comment by qwertyyb** [comment]
这个问题确实是存在的，在下个版本中我修复一下

**Comment by JonyChuh** [comment]
赞！看到已经修复了，非常棒！在切换中英文时，你们非常贴心地设计了两种提示方式可供选择，一种是光标跟随提示，另一种是屏幕居中提示。我有一个小小的建议，能否将这两种提示方式作为附加选项，由用户根据需要开启，同时把菜单栏的图标设计为线性图标、填充图标来与英文、中文相对应，就像Mac系统自带的输入法那样，这样很直观，只要看一眼菜单栏的输入法图标就能知道现在是什么输入状态。我说一下，为什么会有这种想法，现在视频教程似乎成了人人都会的技能，大家都需要录屏，而在录屏的时候始终有输入法的切换提示成了一种干扰因素，所以既能知道当前的输入法状态，又能悄无声息地完成输入法切换，那就太好了。

**Comment by qwertyyb** [comment]
目前中英文的提示方式是可以配置为不显示的，菜单栏也有一个中英文提示的菜单(中/英)
至于你说的

> 把菜单栏的图标设计为线性图标、填充图标来与英文、中文相对应，就像Mac系统自带的输入法那样

我没太理解？是说把菜单栏中系统输入法位置的那个图标按当前的输入模式来显示不同的图标吗？

**Comment by JonyChuh** [comment]
中英文提示可以配置为不显示，但就不清楚当前的输入法状态是什么，像我日常的工作软件是Photoshop，需要经常性切换中英文状态，等到敲击键盘了才知道当前的输入法状态是什么，然后再去切换。虽然中英文状态也是可以显示在菜单栏，但相信很多人跟我一样，不会让它显示在本就空间不足的菜单栏上，既不美观也占地方，一个图标位置也解决就最好了。我建议根据当前的输入模式显示不同图标，比如以下的显示方式，纯属个人建议的一种显示方式，审美不一定在线。
![填充式icon](https://github.com/qwertyyb/Fire/assets/138984173/2405eab1-2576-49fd-9cd2-9f8d4c69c8ac)
![线性icon1](https://github.com/qwertyyb/Fire/assets/138984173/12a53af1-dc42-4778-b2b0-b31859022ca1)
![线性icon2](https://github.com/qwertyyb/Fire/assets/138984173/c0eaa72d-7e0c-4b6b-b401-fa95f9a26b27)

**Comment by qwertyyb** [comment]
我大概get到你的意思了，目前状态栏是有两个输入法相关的图标，一个是指示中英文的图标，另一个是业火输入法的logo图标，你是期望这两个图标二合一，去掉第一个，把第一个的中英文指示的能力融合到第二个菜单栏图标中，把这个图标做成动态的按中英文自动切换的样式对吧？

**Comment by JonyChuh** [comment]
嗯嗯，是这么个意思。一定有人更喜欢当前现行的显示方式，这个建议只是个人想法，采不采纳没关系、不重要。

**Comment by qwertyyb** [comment]
这个想法确实很好
难点应该是在技术实现上，据我所知，目前MacOS似乎没有针对输入法程序开放如上所说的第二个菜单栏图标的动态化能力
我可以去调研尝试一下能否实现

**Comment by JonyChuh** [comment]
谢谢

**Comment by qwertyyb** [comment]
这里我调研尝试了一下，目前技术上确实是实现不了。
因为这里的图标目前是放在一个配置中(info.Plist)，系统在加载输入法的时候，去加载这个配置以获取这个图标的路径，而系统的加载时机是完全依赖MacOS系统的，输入法程序没办法介入影响这一行为。所以目前的所有输入法程序应该都没有办法做到在运行时更换这个图标。
如果你那边有输入法能做到类似的效果可以告诉我，我可以再研究研究。我也会关注苹果官方的动态，在技术可行的情况下，及时支持此特性。
另外，我这边提了一个PR #124 ，增加了一个特性，可以保存状态栏上中英文指示图标的位置，防止每一次重启或者切换输入法后此状态项位置重置。你可以通过按下command键，把这个状态挪到系统输入法切换的图标旁以方便查看实时状态。

**Comment by JonyChuh** [comment]
谢谢！的确，很多想法的实现受到MacOS系统的限制，非常感谢你们所作的尝试，希望这个中英文指示图标的大小、样式可以做得美观一点，建议尽量不要用中文字，个人感觉中文字显示在菜单上显得很突兀，既不协调也不美观。
