### ISSUE TITLE
非常感谢作者,弄下来不用配置,完全符习惯. 提个建议哈.

### ISSUE THREAD

**Issue by eAtmApp** [qwertyyb/Fire#120]
com.apple.loginwindow
#登录窗口

com.apple.SecurityAgent
#权限验证

com.apple.LocalAuthenticationRemoteService
#系统设置->密码

com.apple.Touch-ID-Settings.extension
#更改密码

能把这两个包默认英文吗
一个是用户登录窗口
一个是管理员权限验证窗口

百度/搜狗/清风 这几个都用过,这个问题都存在
经常会在密码输入窗口出现'中文输入'
也是因为这原因才另外找输入法

我不知道别人有没有这个问题, 
也有可能因为我把系统自带的ABC给删了造成的 -_-!

因为不熟悉xcode, 依赖库的问题折腾了半天才跑起来,
然后才发现系统日志中能看到 -_-!

这两个包名都不知道是什么应用,估计要找配置文件改了.
建议作者在软件内置加上这两个配置,
我估计是强迫症研究了一下午 -_-!

**Comment by qwertyyb** [comment]
合理的诉求，我会尽快支持

**Comment by eAtmApp** [comment]
> 合理的诉求，我会尽快支持

刚发现管理权限的密码输入框 并不只一种
在 系统设置中 允许未知应用启动 的输入框又是另外一个包名
如果这样一个个加感觉有些太局限

"自动切换 保持应用最后使用的输入模式" 这个功能 是不是并没有保存到配置文件呢?
如果保存到配置文件,可能就完美了.

**Comment by qwertyyb** [comment]
自动切换 保持应用最后使用的输入模式

这个配置项目前是运行时状态，如果应用重新启动就会丢失状态，你的意思是说把这个状态持久化，即使重新启动也保持上一次应用的输入模式吗？

我觉得这个想法非常好哎

**Comment by eAtmApp** [comment]
> 自动切换 保持应用最后使用的输入模式
> 
> 这个配置项目前是运行时状态，如果输入法重新启动就会丢失状态，你的意思是说把这个状态持久化，即使输入法重新启动也保持上一次应用的输入模式吗？
> 
> 我觉得这个想法非常好哎

对啊,就是这个意思

**Comment by eAtmApp** [comment]
@qwertyyb 
作者能否建个群
我对xcode开发是新手
不是很熟
但也希望来完善这个项目.

**Comment by qwertyyb** [comment]
@eAtmApp 加个微信吧 qwertyyb123

**Comment by qwertyyb** [comment]
这里已处理支持
