### ISSUE TITLE
报告一个bug

### ISSUE THREAD

**Issue by eAtmApp** [qwertyyb/Fire#121]
在中文状态下,如果想不切换,也不用符号(;)临时切换,
直接输入英文: aBcD+回车(注意大小写)
最终会变成:BDac
这里应该有逻辑问题,当有字符没上屏时,shift+[a-z] 不能让大写先上屏

------------------------

又碰到一个.
默认设置shift切换中英文
在微信中输入时, 微信中是用shift+回车 换行
然后会随机性的,很频繁的出现中文来回切换

**Comment by qwertyyb** [comment]
问题1、2都已确认，我这边尽快处理

**Comment by qwertyyb** [comment]
@eAtmApp 经过调试验证，问题2没有办法修复。
造成问题2的根本原因是，在微信中输入时，当所有字符都已上屏后，按下回车键，正常情况下，回车键事件应该先转发给输入法，但是在微信中，微信完全拦截了回车键，输入法没有办法收到回车键的事件。

所以这里的案例是，在微信中按下shift，按下回车，松开回车，松开shift，由于回车按键的事件输入法接收不到，所以对于输入法来说，输入法接收到的事件是按下shift，松开shift，所以就会进行中英文切换。

**Comment by qwertyyb** [comment]
我试了搜狗输入法和清歌输入法，都有同样的问题

**Comment by eAtmApp** [comment]
@qwertyyb 我这边试清歌输入法是正常的- 清歌2.15 十周年纪念版(3900)
百度输入法应该也正常, 我用过一段时间百度, 没有出现这个问题

这个问题在微信上面一下就出现了,如果遇到过肯定知道
-----------------------------------------------------

工进
 
嘌
地
加载
中
 
枯井
谭
哪
畕
 
嘌
  进
黔西南

时
lksf 
加 
flksf 
lkf时
fk 辕
"吉
fl 时
flk时
flks进
檑
fk 
sf 
----------------------------
这上面部分是清歌输入的,
下面部分是业火输入的.
百度的给删了
我在微信经常会回车多行输入的
这种情况如果有,我这种习惯性换行的 必定会知道,因为这情况没法用了都

**Comment by qwertyyb** [comment]
大概了解了，清歌和搜狗输入法应该是把松开shift键和按下shift键的时间设置的比较短，我这边也可以把0.3s的时间调短试一下

**Comment by eAtmApp** [comment]
-_- 如果暂时真无解,可能又只能装上百度来用了
百度能自己改配置 自己加包名来默认英文
清歌的配置文件中只存在.app, 没有包名,像密码输入框的那种不是.app, 加不进去

------------------
刚才用的清歌输入法, 把电脑唤醒登录时,密码错了好几遍, 就是中英文导致的, 
这应该是删了ABC才会导致这一系列的问题

**Comment by eAtmApp** [comment]
再回想一下,当初删ABC, 可能就是因为在密码输入框 会自动切换到ABC
然后切换回其它应用时, 仍然是ABC, 人这时候没反应过来,又要删了换输入法重来, 这样才会有删ABC的念头,

所以还是严重建议作者能加入个开关 '将 应用最后输入模式保存到配置文件'

**Comment by eAtmApp** [comment]
> 大概了解了，清歌和搜狗输入法应该是把松开shift键和按下shift键的时间设置的比较短，我这边也可以把0.3s的时间调短试一下

@qwertyyb 
我把delayInterval值改成了0.1 能符合我的输入习惯
0.2都不行
这个值可能因为而异

**Comment by eAtmApp** [comment]
这里存一份,省得git给弄没了-_-!

        //************************************************************************************
        //处理部分应用热键消息绕过输入法
        //注册权限
        var monitorMask=NSEvent.EventTypeMask.flagsChanged
        if let bool = kCFBooleanTrue {
            let opts = NSDictionary(object: bool,
                                    forKey: kAXTrustedCheckOptionPrompt.takeUnretainedValue() as NSString) as CFDictionary
            if AXIsProcessTrustedWithOptions(opts) {
                monitorMask=[NSEvent.EventTypeMask.keyDown,NSEvent.EventTypeMask.keyUp,NSEvent.EventTypeMask.flagsChanged]
            }
        }
        
        NSEvent.addGlobalMonitorForEvents(matching: monitorMask,handler: {
            (event: NSEvent) in
            
            //原处理代码
            if !InputSource.shared.isSelected() {
                return
            }
            if event.type==NSEvent.EventType.flagsChanged{
                _ = self.inputController?.flagChangedHandler(event: event)
            }
            
            //处理按键消息绕过输入法
            struct easy {
                struct Keycode {
                    static let shift                     : UInt16 = 0x38
                    static let rightShift                : UInt16 = 0x3C
                }
                
                //按键状态
                static var _is_shift_down=false
                
                //处理状态
                static var _handled=false
                
                static func log(_ message: Any) {
                    NSLog("SRLog: \(message)")
                }
                
                //判断是否shift键消息
                static func is_shift_msg(event:NSEvent)-> Bool
                {
                    return event.keyCode==Keycode.shift || event.keyCode==Keycode.rightShift
                }
                
                //按键消息
                static func key_msg(event:NSEvent)
                {
                    let shiftFlag = NSEvent.ModifierFlags.shift
                    
                    if event.type == .flagsChanged {
                        if event.modifierFlags.contains(shiftFlag) {
                            log("Shift pressed down")
                            if  !_is_shift_down {
                                _is_shift_down=true
                                _handled=false
                            }
                        } else {
                            log("Shift pressed up")
                            _is_shift_down=false
                        }
                    }
                }
                
                //模拟
                static func fake(_self:CandidatesWindow,event:NSEvent)
                {
                    //shift
                    //NSEvent: type=FlagsChanged loc=(823.369,348.935) time=4367.4 flags=0x20102 win=0x0 winNum=0 ctxt=0x0 keyCode=56
                    //NSEvent: type=FlagsChanged loc=(823.369,348.935) time=4367.5 flags=0x100 win=0x0 winNum=0 ctxt=0x0 keyCode=56
                    
                    //cmd
                    //NSEvent: type=FlagsChanged loc=(823.369,348.935) time=4370.1 flags=0x100108 win=0x0 winNum=0 ctxt=0x0 keyCode=55
                    
                    //a
                    //NSEvent: type=KeyDown loc=(823.369,348.935) time=4373.3 flags=0x100 win=0x0 winNum=0 ctxt=0x0 chars="a" unmodchars="a" repeat=0 keyCode=0
                    
                    //shift+cmd
                    //SRLog: NSEvent: type=FlagsChanged loc=(3034.1,697.159) time=12373.2 flags=0x12010a win=0x0 winNum=0 ctxt=0x0 keyCode=55
                    
                    //没处理 并且不是shift消息
                    if !_handled && !is_shift_msg(event:event) {
                        let modifierFlags: NSEvent.ModifierFlags = [.command , .shift]
                        
                        if let vEvent = NSEvent.keyEvent(with: NSEvent.EventType.flagsChanged
                                                         , location:event.locationInWindow
                                                         , modifierFlags: modifierFlags
                                                         , timestamp: event.timestamp
                                                         , windowNumber: event.windowNumber
                                                         , context: nil
                                                         , characters: ""
                                                         , charactersIgnoringModifiers: ""
                                                         , isARepeat: event.isARepeat
                                                         , keyCode: 55) //command keycode
                        {
                            _ = _self.inputController?.flagChangedHandler(event: vEvent)
                            
                            log("模拟cmd键消息")
                            _handled=true
                        }else{
                            log("构造NSEvent失败")
                        }
                    }
                    
                    //处理标记按键状态
                    key_msg(event: event)
                }
            }
            
            easy.fake(_self: self, event: event)
        })
        
        //************************************************************************************

**Comment by Acyco** [comment]
现在改得有时候写文件或写代码经常按shift经常切换不了中英状态 我是昨天才更新 这两天用得我好难受
