### ISSUE TITLE
提个小需求-支持分号和引号选词

### ISSUE THREAD

**Issue by stevenlii** [qwertyyb/Fire#126]
可以增加这个功能吗，非常需要，用数字选词太慢了，目前我知道的是sogou和百度支持

**Comment by qwertyyb** [comment]
好👌

**Comment by qwertyyb** [comment]
@stevenlii 我为此特意下载了搜狗输入法，并没有你所说的分号和引号选词，你能解释一下分号和引号选词是怎么一个选词逻辑吗？
