### ISSUE TITLE
请把最大候选词数量由9改为10

### ISSUE THREAD

**Issue by free-150** [qwertyyb/Fire#131]
在输入一些按顺序的词不好对齐候选尤其在翻页后易错位，比如：罗马数字ⅰ ⅱ iii ...

**Comment by qwertyyb** [comment]
最大候选词数量之所以是9个，是刚好对应于选词数字键1-9。
如果有10个候选词，会有一个词没有选词键。
针对这个问题，你有什么解决方案吗？

**Comment by free-150** [comment]
现在比较现代的输入法都支持10个候选了。用数字0选第10个

**Comment by qwertyyb** [comment]
“在输入一些按顺序的词不好对齐候选尤其在翻页后易错位” 你这么说的话，我感觉我对这句话有点不太理解了，截个图或者再详细说明一下“对齐候选”
