### ISSUE TITLE
如何通过命令切换中英文输入状态

### ISSUE THREAD

**Issue by Thesoul20** [qwertyyb/Fire#134]
在Vim 中，退出编辑模式后可以直接将输入法切换为英文模式（对于系统自带的输入法，可以使用 im-select 这个工具来实现）。但是对于 Fire 来讲，无论是英文输入状态还是中文输入状态，im-select 检测到的都是同一个结果。
```shell
im-select
com.qwertyyb.inputmethod.Fire
```

那么在 Fire 输入法中，如何通过一个命令来切换中英文输入法的状态呢？

**Comment by qwertyyb** [comment]
第三方输入法，我试了搜狗拼音、搜狗五笔、清歌输入法，它们内部的中英文切换都没有办法通过 im-select 去获取，这里应该是系统限制。
最近更新了逻辑，在从其它输入法切换至此输入法后，会固定为中文输入模式。这个特性可以和自带的 ABC 输入法配合，用自带的 ABC 输入法作英文输入，业火输入法作中文输入。
至于通过命令行切换中英文输入法的状态，预计会在下个版本中添加

**Comment by Thesoul20** [comment]
感谢！！！
