### ISSUE TITLE
加入手动调整候选顺序的功能

### ISSUE THREAD

**Issue by liaogang** [qwertyyb/Fire#43]
这个项目真的很好，生成的程序干净，体积小，出字速度快。感谢作者的付出!

有一个小问题, 比如我输入 e,  候选的有 "月， 有， .."
有应当是高频词，优先排在月前面，希望这里可以优化一下，加入手动调整候选顺序的功能

**Comment by qwertyyb** [comment]
会考虑支持此能力

**Comment by qwertyyb** [comment]
此能力已支持
