### ISSUE TITLE
考慮搬到 Gitee？

### ISSUE THREAD

**Issue by ShikiSuen** [qwertyyb/Fire#44]
GitHub 越來越難上了。至少在 Gitee 有一個官方 mirror 也好。

<img width="581" alt="image" src="https://user-images.githubusercontent.com/3164826/156203611-9d0e3f20-84e5-4ee9-a02e-06c05351d321.png">

**Comment by qwertyyb** [comment]
https://gitee.com/qwertyyb/Fire done
