### ISSUE TITLE
issues deleted

### ISSUE THREAD

**Issue by yutent** [qwertyyb/Fire#45]

**Comment by qwertyyb** [comment]
欢迎贡献词库

**Comment by yutent** [comment]
> 

https://github.com/yutent/wb-table

这是我自己制作的词库项目,  还有部分功能未完成, 不过词库可以使用下载了。

**Comment by qwertyyb** [comment]
这里目前看上去确实还有些问题，还没办法直接使用

> > 
> 
> https://github.com/yutent/wb-table
> 
> 这是我自己制作的词库项目, 还有部分功能未完成, 不过词库可以使用下载了。

**Comment by yutent** [comment]
> 这里目前看上去确实还有些问题，还没办法直接使用

啥问题? 我自己目前在用, 除了词汇顺序现在还不太合理之外, 目前正常

**Comment by ShikiSuen** [comment]
外部援助的词库内容最好政审一下，无论对方是谁。
虽说有 MIT 免责条款，但一旦专案内不小心掺了政治敏感的东西的话，除了用 git-filter-repo/branch 洗仓库以外没别的方法。

**Comment by ShikiSuen** [comment]
@yutent 如果您自己有政审过您的词库的话，可以在专案的 readme.md 里面写明说你仓库的内容可以合法地在国内传播。
