### ISSUE TITLE
偏好设定视窗内的 App 清单在内容为空的时候、滚动条的位置不对劲

### ISSUE THREAD

**Issue by ShikiSuen** [qwertyyb/Fire#51]
首先是滚动条得贴最右边。估计是 view 的 constraints 没弄好吧……但可能在 SwiftUI 里面有别的解释概念，我对 SwiftUI 不熟。

其次是：App 清单内容为空的时候，没有什么需要卷动的内容吧？

<img width="559" alt="image" src="https://user-images.githubusercontent.com/3164826/159170967-7eeb6cd9-eaa3-423f-8710-8d7553ee3aa6.png">

问题对应输入法版本 v0.6.0。

**Comment by qwertyyb** [comment]
已处理，感谢反馈
