### ISSUE TITLE
问个关于输入法 IMK 组字区行为的问题。

### ISSUE THREAD

**Issue by ShikiSuen** [qwertyyb/Fire#55]
<img width="388" alt="image" src="https://user-images.githubusercontent.com/3164826/169568452-cdc972f2-2549-45f4-9441-be86cbf3b90b.png">
这样看起来像是 IMK 组字区内有一个空格。
请问这样设计是为了确保「某些按键会被输入法捕捉到」吗？还是有别的考量？

P.S.: 可以考虑开启 Discussion 版面，这样就不用开工单来讨论了。

**Comment by qwertyyb** [comment]
当初始码在候选框中时，输入框这里是特意填充了一个空格，是因为在实际运行过程中发现，如果不填充一个空格，按删除键的时候，输入框中的原有的字符就也会被删除。
猜测可能是因为delete key事件同时被派发给了输入法和输入框，所以输入框也会响应delete key事件，把原有的字符删掉。所以这里填充了一个空格，每次删除的时候，删除的就是这个空格，删除之后如果还能再删就立刻再补上一个空格，通过这种方法来避免规避这个问题。
当然，这是把原始码放在候选窗口才有的问题，如果把原始码放在输入框中（就像自带输入法那样）就没有这个问题了。这里可以通过设置来配置
<img width="510" alt="image" src="https://user-images.githubusercontent.com/16240729/169629603-bc3e378e-6170-4a1a-aca1-b9e73db0aefb.png">

https://github.com/qwertyyb/Fire/blob/master/Fire/FireInputController.swift#L63
你可以把这一行改成
```
selected = ""
```
来验证

**Comment by qwertyyb** [comment]
https://user-images.githubusercontent.com/16240729/169629968-647b36ed-4fad-4a51-8f90-edc83810292d.mov

就像上面这样，奇怪的是，好像只有非apple系应该才有这个问题

**Comment by ShikiSuen** [comment]
@qwertyyb 谢谢。看来雅虎奇摩输入法的一点通选单在 word 内无法使用方向键控制的原因就是这个了。
（威注音的酷音风格符号选单也是因为这个原因被我雪藏了起来，刚刚测试发现确实是这样。）
我回头再试试看这里是否可以用一个 unprintable character 来取代。

**Comment by ShikiSuen** [comment]
@qwertyyb 受影響的程式包含 macOS 內建的終端機、以及幾乎所有第三方終端機應用、還有 MS Word。

P.S.: Discussion 版面開放可以在倉庫設定內找到。

**Comment by ShikiSuen** [comment]
結論是還是用目前的設計比較好。
用 unprintable character 的話，下畫線還在（會變成一個點），attributedString 得去掉下畫線。
而且，即便如此，Word 內還是會顯示一個 mojibake 豆腐記號。

結案。
