### ISSUE TITLE
能不能新增一个用户自定义词库

### ISSUE THREAD

**Issue by yingguqing** [qwertyyb/Fire#63]
用户自定义一些词组，保存下来

**Comment by yingguqing** [comment]
![image](https://user-images.githubusercontent.com/6702678/174010690-dea68b0c-01b7-4753-960d-c27077e4d865.png)
这种情况不知道怎么出现的

**Comment by qwertyyb** [comment]
这个确实也是挺实用的能力，我后面加上

**Comment by qwertyyb** [comment]
已支持
