### ISSUE TITLE
在arm的电脑上用Xcode进行构建时，出现复制三个文件的错误

### ISSUE THREAD

**Issue by Acyco** [qwertyyb/Fire#69]
![image](https://user-images.githubusercontent.com/9018466/175837186-99a701d6-3552-44b4-88de-51e189b4536a.png)
找不到那三个文件的路径.

**Comment by qwertyyb** [comment]
目前手头上没有M1或M2的mac, 调试不了，也不知是什么问题

**Comment by Acyco** [comment]
好的，谢谢

**Comment by yingguqing** [comment]
这个错误只需要修改CONFIGURATION_BUILD_DIR属性的值为build/Debug就可以了。

**Comment by qwertyyb** [comment]
> 这个错误只需要修改CONFIGURATION_BUILD_DIR属性的值为build/Debug就可以了。

@yingguqing 改了后怎么调试呢？

**Comment by qwertyyb** [comment]
> ![image](https://user-images.githubusercontent.com/9018466/175837186-99a701d6-3552-44b4-88de-51e189b4536a.png)
> 找不到那三个文件的路径.

这里的问题大概知道是怎么回事了，应该是/Library/Input Methods这个文件夹的权限问题，所以写入失败了，需要修改下文件夹的权限

**Comment by Acyco** [comment]
改了地址可以运行，没法调试，不改给权限还是照样找不到

**Comment by yingguqing** [comment]
我调试的方法是安装作者打包好的pkg，然后直接在xcode里运行就可以了。

**Comment by GanZhiXiong** [comment]
> 这个错误只需要修改CONFIGURATION_BUILD_DIR属性的值为build/Debug就可以了。

@qwertyyb @yingguqing 

按照这个修改后，却报了另外一个错误：
```
Library not found for -lPods-Fire
```

**Comment by qwertyyb** [comment]
@GanZhiXiong 删除掉Build Phases中的-lPods-Fire,重新运行即可

**Comment by ShikiSuen** [comment]
Fire 要不要改成 user space 的输入法？放在 ~/Library/Input Methods/ 内。
这样就没有权限问题了。

**Comment by Acyco** [comment]
这样系统能识别吗？

**Comment by ShikiSuen** [comment]
@Acyco 能啊。威注音就这么做的。甚至说威注音必须安装在使用者目录下。
