### ISSUE TITLE
可否增加一些这样的特性。比如在中文状态输入time或date这样的能输出格式化的日期

### ISSUE THREAD

**Issue by Acyco** [qwertyyb/Fire#70]
![image](https://user-images.githubusercontent.com/9018466/175926893-5639546f-e310-4fc6-ac36-e98ab3f34a2a.png)

![image](https://user-images.githubusercontent.com/9018466/175927069-8eb1257a-8364-4d64-a5c0-9dfafa1b38a8.png)

像这样的功能 ， 本来我是想把你的项目fork下来，我增加功能 再提交给你的，但构建不能通过。

**Comment by Acyco** [comment]
还有能增加一个能自定义一些符号，在中文状态能使用半角符号，比如:＋ － × ＝这些符号能在中文状态的时候是 + - * =，，写代码

**Comment by qwertyyb** [comment]
符号这里确实是需要优化一下，目前这样的实现确实不太好，后面我会把这个能力加上
上面的快捷输入有些场景确实也是很需要的，也mark上，一并加上

**Comment by Acyco** [comment]
对了，能增加一个右shift切换中英文状态 。 谢谢

**Comment by qwertyyb** [comment]
> 对了，能增加一个右shift切换中英文状态 。 谢谢

这里还需要特意区分左右按键吗？

**Comment by yingguqing** [comment]
> > 对了，能增加一个右shift切换中英文状态 。 谢谢
> 
> 这里还需要特意区分左右按键吗？

新增个fn键切换中英文吧。笔记本的fn键比较容易按

**Comment by qwertyyb** [comment]
左shift, 右shift, fn键，我这周加一下

**Comment by Acyco** [comment]
> > 对了，能增加一个右shift切换中英文状态 。 谢谢
> 
> 这里还需要特意区分左右按键吗？

需要。 因为有软件或游戏 左边的shift是里面的按键和输入法冲突了， 比如Minecraft它的左边是蹲下操作

**Comment by qwertyyb** [comment]
添加了左shift, 右shift, fn键切换，添加了标点符号的自定义 @Acyco @yingguqing

**Comment by Acyco** [comment]
看到了，我已经更新了 还有标点符号 。。 太谢谢你了。。 好厉害啊，羡慕会swift的大佬。。。

**Comment by ShikiSuen** [comment]
@Acyco Swift 與 C# 差不多簡單吧，至少比 C++ 好用多了。
