### ISSUE TITLE
输入法在Alfred 4里面没法输入，数字都不行

### ISSUE THREAD

**Issue by yingguqing** [qwertyyb/Fire#72]
在Alfred 4的输入框里，任何内容都输入不了，但是当前的输入法是Fire没错

**Comment by yingguqing** [comment]
复制、粘贴可以，删除、数字、字母，切换中英文这些都不行

**Comment by qwertyyb** [comment]
我在开发中有遇到过，一开始都是正常的，忽然某个应用的按键全部失效，感觉应该是macos的问题，只能重启，你可以重启试试
