### ISSUE TITLE
保留应用最后使用状态有点问题

### ISSUE THREAD

**Issue by yingguqing** [qwertyyb/Fire#76]
我在微信里是中文输入，我设置了xcode为英文输入。我从微信切到xcode能正常变成英文输入。但是我切回微信时，一样是英文输入。

**Comment by yingguqing** [comment]
有接另外的显示器的时候，在一个屏幕上放xcode，另一个屏幕上放微信。微信最后使用中文，当点击了另一个屏幕的xcode，再回到微信的时候，微信不能恢复中文，会变成英文模式，如果微信和xcode在同一个屏幕是完全没有问题的。

**Comment by qwertyyb** [comment]
已定位到问题，后面发版本修复
