### ISSUE TITLE
打字统计貌似有点问题

### ISSUE THREAD

**Issue by Acyco** [qwertyyb/Fire#80]
<img width="526" alt="image" src="https://user-images.githubusercontent.com/9018466/180260988-118ef15a-9ec4-4e93-bc62-7862be5e3e1e.png">
<img width="564" alt="image" src="https://user-images.githubusercontent.com/9018466/180261573-04a3022b-7e57-4635-b98d-b119d152aa72.png">

今天才不到几分钟，可是统计那里就显示出我打了2500多字， 这个是不是有点问题啊？

**Comment by qwertyyb** [comment]
可以查库看一下，是不是有输入字符，统计的存储位置是
~/Library/Application Support/com.qwertyyb.inputmethod.Fire/statistics.db
这里使用了sqlcipher加密，加密的密码存放在钥匙链中，搜索Fire，复制出密码，解码下数据库，看下内容

**Comment by qwertyyb** [comment]
不过看数据，感觉确实是有些问题，应该是时间统计那里有些问题，我后面看一下

**Comment by Acyco** [comment]
<img width="499" alt="image" src="https://user-images.githubusercontent.com/9018466/180480464-44f28165-5fba-4909-b23b-3f2b6bddbef0.png">
23号 我一个字也没输入就1300多字

**Comment by Acyco** [comment]
用你说的那个 我查出来 应该是你程序的bug
<img width="1027" alt="image" src="https://user-images.githubusercontent.com/9018466/180583427-b11446a4-1979-42dd-aeb9-9695458fc483.png">

**Comment by qwertyyb** [comment]
问题已处理
