### ISSUE TITLE
满4码唯一候选词直接上屏 功能有时候无效

### ISSUE THREAD

**Issue by cgistar** [qwertyyb/Fire#93]
版本：0.13.4
编码方案是：五笔
勾选 满4码唯一候选词直接上屏

尝试输入：五笔字形[空格]，会上屏： ggttp陚

**Comment by qwertyyb** [comment]
![image](https://user-images.githubusercontent.com/16240729/201307789-3037f8bd-52f5-49bd-8bb1-de9982aee7c5.png)
这个五笔字形非唯一候选词，所以不会上屏

**Comment by cgistar** [comment]
五笔字型四个字原来是可以直接打的啊，我尝试的是先打 五笔，再打字型，再打空格，上屏内容是ggttp陚，会有字母上屏
